name: lint

on:
  pull_request:
    branches:
      - master

jobs:
  composer_lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'

    - name: Install Composer Dependencies
      run: composer install --no-progress --no-suggest

    - name: Run Composer Lint
      run: composer lint

    - name: Set Composer Lint Status Check
      run: echo ::set-output name=lint_result::success

  node_lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install Node.js Dependencies
      run: npm install

    - name: Run Node Lint
      run: npm run lint:js

    - name: Set Node Lint Status Check
      run: echo ::set-output name=lint_result::success

  css_lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install Node.js Dependencies
      run: npm install

    - name: Run Node Lint
      run: npm run lint:css

    - name: Set Node Lint Status Check
      run: echo ::set-output name=lint_result::success

  approvals:
    runs-on: ubuntu-latest
    needs:
      - composer_lint
      - node_lint
      - css_lint

    steps:
    - name: Check Composer Lint Result
      run: echo "Composer Lint Result ${{needs.composer_lint.outputs.lint_result}}"

    - name: Check Node Lint Result
      run: echo "Node Lint Result ${{needs.node_lint.outputs.lint_result}}"

    - name: Check CSS Lint Result
      run: echo "Node Lint Result ${{needs.css_lint.outputs.lint_result}}"
